GET http://localhost:5000/kelas_siswa

###

GET http://localhost:5000/kelas_siswa/2

###

POST http://localhost:5000/kelas_siswa
Content-Type: application/json

{
    "nama_kelas" : "ot bd bd bd bd bd bd bd bd bdb bd"
}

###

PATCH http://localhost:5000/kelas_siswa/2
Content-Type: application/json

{
    "nama_kelas" : "kelas 2c ng ng ng ng",
    "wali_kelas" : "frederic alfaris"
}

###

DELETE http://localhost:5000/kelas_siswa/25